docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,16 +1,27 @@
-name: GHAction z2obraz
+name: GHAction example
 
 on:
   workflow_dispatch:
   push:
     tags:
     - 'v*'
+  pull_request:
+    branches:
+      - '**'
+
+env:
+  # Ustawienie nazwy użytkownika do GHCR
+  GHCR_USERNAME: ${{ github.repository_owner }}
+  SHA: ${{ github.sha }}
 
 jobs:
-  ci_step:
-    name: Build, tag, and potentially push Docker image to GitHub Container Registry
+  build-and-scan:
+    name: Build, scan, and push Docker image to GHCR
     runs-on: ubuntu-latest
-      
+    permissions:
+      contents: read
+      security-events: write
+
     steps:
       - name: Check out the source_repo
         uses: actions/checkout@v4
@@ -19,52 +30,66 @@ jobs:
         id: meta
         uses: docker/metadata-action@v5
         with:
-          images: ${{ vars.DOCKERHUB_USERNAME }}/z2obraz
+          images: ghcr.io/${{ github.repository }}
           flavor: latest=false
           tags: |
             type=sha,priority=100,prefix=sha-,format=short
             type=semver,priority=200,pattern={{version}}   
 
-      - name: Docker Setup QEMU
-        uses: docker/setup-qemu-action@v3.0.0
-                    
-      - name: Docker Setup Buildx           
-        uses: docker/setup-buildx-action@v3.3.0
+      - name: QEMU set-up
+        uses: docker/setup-qemu-action@v3
 
-      - name: Login to DockerHub
+      - name: Buildx set-up
+        uses: docker/setup-buildx-action@v3
+
+      - name: Login to GHCR
         uses: docker/login-action@v3
         with:
+          registry: ghcr.io
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build and push Docker image
-        id: docker-build-push
+      - name: Build Docker image
+        id: build
         uses: docker/build-push-action@v5
         with:
           context: .
           file: ./Dockerfile
           platforms: linux/amd64,linux/arm64
           push: false
-          cache-from: |
-            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/z2obraz:cache 
-          cache-to: |
-            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/z2obraz:cache  
           tags: ${{ steps.meta.outputs.tags }}
 
-      - name: Docker Scout - CVE Analysis
+      - name: Analyze for critical and high CVEs
         id: docker-scout-cves
         uses: docker/scout-action@v1
         with:
           command: cves
-          image: ${{ vars.DOCKERHUB_USERNAME }}/z2obraz:${{ steps.meta.outputs.version }}
+          image: ${{ steps.meta.outputs.tags }}
           sarif-file: sarif.output.json
           summary: true
+      
+      - name: Upload SARIF result
+        id: upload-sarif
+        uses: github/codeql-action/upload-sarif@v2
+        with:
+          sarif_file: sarif.output.json
 
-      - name: Determine CVE Severity
-        id: determine-cve-severity
-        run: echo "::set-output name=has_critical_or_high::$(grep -q 'critical\|high' sarif.output.json && echo true || echo false)"
+      - name: Check vulnerability scan results
+        run: |
+          CRITICAL_COUNT=$(jq '.runs[].results | map(select(.ruleId | contains("CRITICAL"))) | length' sarif.output.json)
+          HIGH_COUNT=$(jq '.runs[].results | map(select(.ruleId | contains("HIGH"))) | length' sarif.output.json)
+          if [ "$CRITICAL_COUNT" -gt 0 ] || [ "$HIGH_COUNT" -gt 0 ]; then
+            echo "Critical or High vulnerabilities found. Failing the job."
+            exit 1
+          fi
 
-      - name: Push Docker image if no critical or high CVEs
-        if: steps.determine-cve-severity.outputs.has_critical_or_high == 'false'
-        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/z2obraz:${{ steps.meta.outputs.version }}
+      - name: Push Docker image to GHCR
+        if: success()
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: ./Dockerfile
+          platforms: linux/amd64,linux/arm64
+          push: true
+          tags: ${{ steps.meta.outputs.tags }}
 
